language: node_js
jobs:
  include:
    - stage: deploy
      script:
        - REPO=dnivra26.github.io
        - rm -rf ${REPO}
        - git clone git://github.com/dnivra26/${REPO}.git
        - rm -r ${REPO}/*
        - cp -r public/* ${REPO}/
        - cd ${REPO}
        - git config user.email ${email_id}
        - git config user.name dnivra26
        - git add .
        - git commit -m $TRAVIS_COMMIT
        - git push "https://#{github_token}@github.com/dnivra26/${REPO}.git" master
        