baseURL = "https://dnivra26.github.io/"
languageCode = "en-us"
title = "Arvind Thangamani"
theme = "coder"

languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Arvind Thangamani" # Author's name.
    info = "Music, Books and may be Computers..." # Author's job title or info.
    description = "Yusuke Ishimi's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/arvind.jpeg" # Contain the path of the optionnal avatar in the static folder.


    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/dnivra26/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/dnivra26/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "https://medium.com/@dnivra26"
[[menu.main]]
    name = "Goodreads"
    weight = 2
    url  = "https://www.goodreads.com/dnivra26"    